# Setup
title:               The Dragon Portfolio
tagline:             A 100 year portfolio - implemented
description:         Suggestion for how you, as an European, investor could implement the dragon portfolio.
url:                 https://driftwoodpalace.github.io/Dragon-Portfolio
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag  
  - jekyll-sitemap
  - jekyll-feed

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Jörg Machalkin
  url: https://twitter.com/DriftwoodPalace
  email: -

# Custom vars
version: 1.0.0
